development:
  adapter: postgresql
  encoding: unicode
  database: EscuelaApp_development
  pool: 5
  username: postgres
  password: megapanza17
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: EscuelaApp_test
  pool: 5
  username: postgres
  password: megapanza17
  host: localhost
